### ISSUE TITLE
friendship_request_canceled cause TypeError: Model instances without primary key value are unhashable

### ISSUE THREAD

**Issue by timur-orudzhov** [revsys/django-friendship#100]
I've come across an issue:

django: 2.2.3
django-friendship: 1.8.1

Traceback:
```
2019-10-24 12:57:57 [ERROR] Internal Server Error: /v1/friendship_requests/11/cancel/
Traceback (most recent call last):
 File "/usr/local/lib/python3.7/site-packages/django/core/handlers/exception.py", line 34, in inner
 response = get_response(request)
 File "/usr/local/lib/python3.7/site-packages/django/core/handlers/base.py", line 115, in _get_response
 response = self.process_exception_by_middleware(e, request)
 File "/usr/local/lib/python3.7/site-packages/django/core/handlers/base.py", line 113, in _get_response
 response = wrapped_callback(request, *callback_args, **callback_kwargs)
 File "/usr/local/lib/python3.7/site-packages/django/views/decorators/csrf.py", line 54, in wrapped_view
 return view_func(*args, **kwargs)
 File "/usr/local/lib/python3.7/site-packages/rest_framework/viewsets.py", line 116, in view
 return self.dispatch(request, *args, **kwargs)
 File "/usr/local/lib/python3.7/site-packages/rest_framework/views.py", line 495, in dispatch
 response = self.handle_exception(exc)
 File "/usr/local/lib/python3.7/site-packages/rest_framework/views.py", line 455, in handle_exception
 self.raise_uncaught_exception(exc)
 File "/usr/local/lib/python3.7/site-packages/rest_framework/views.py", line 492, in dispatch
 response = handler(request, *args, **kwargs)
 File "./api_v1/viewsets/friendship_requests.py", line 105, in cancel
 instance.cancel()
 File "/usr/local/lib/python3.7/site-packages/friendship/models.py", line 157, in cancel
 friendship_request_canceled.send(sender=self)
 File "/usr/local/lib/python3.7/site-packages/django/dispatch/dispatcher.py", line 170, in send
 if not self.receivers or self.sender_receivers_cache.get(sender) is NO_RECEIVERS:
 File "/usr/local/lib/python3.7/site-packages/django/db/models/base.py", line 536, in __hash__
 raise TypeError("Model instances without primary key value are unhashable")
TypeError: Model instances without primary key value are unhashable
```

I think the problem occurs because we generate signal `friendship_request_canceled` when we've already deleted that object.

```python
    def cancel(self):
        """ cancel this friendship request """
        self.delete()
        friendship_request_canceled.send(sender=self)
        bust_cache("requests", self.to_user.pk)
        bust_cache("sent_requests", self.from_user.pk)
        return True
```

**Comment by frankwiles** [comment]
Oooh, interesting and I think you're correct.  Figure it's relatively safe to assume we can send the signal before delete as it's unlikely the delete will fail or a bad action would happen as the result of the signal so I just swapped their positions. Thanks!
