### ISSUE TITLE
Package not compatible with Django 3.2 (django-friendship 1.9.1)

### ISSUE THREAD

**Issue by uri-rodberg** [revsys/django-friendship#129]
If I install Django 3.2rc1 and run tests, I receive the following error messages:

```
Traceback (most recent call last):
  File "/home/travis/build/speedy-net/speedy-net/speedy/core/friends/tests/test_models.py", line 81, in test_if_user1_blocked_user2_friendship_is_removed
    Block.objects.block(blocker=self.user_1, blocked=self.user_2)
  File "/home/travis/build/speedy-net/speedy-net/speedy/core/blocks/managers.py", line 83, in block
    block, created = self.get_or_create(blocker=blocker, blocked=blocked)
  File "/home/travis/virtualenv/python3.6.10/lib/python3.6/site-packages/django/db/models/manager.py", line 85, in manager_method
    return getattr(self.get_queryset(), name)(*args, **kwargs)
  File "/home/travis/virtualenv/python3.6.10/lib/python3.6/site-packages/django/db/models/query.py", line 588, in get_or_create
    return self.create(**params), True
  File "/home/travis/virtualenv/python3.6.10/lib/python3.6/site-packages/django/db/models/query.py", line 453, in create
    obj.save(force_insert=True, using=self.db)
  File "/home/travis/build/speedy-net/speedy-net/speedy/core/blocks/models.py", line 32, in save
    return super().save(*args, **kwargs)
  File "/home/travis/build/speedy-net/speedy-net/speedy/core/base/models.py", line 28, in save
    return super().save(*args, **kwargs)
  File "/home/travis/build/speedy-net/speedy-net/speedy/core/base/models.py", line 13, in save
    return super().save(*args, **kwargs)
  File "/home/travis/virtualenv/python3.6.10/lib/python3.6/site-packages/django/db/models/base.py", line 727, in save
    force_update=force_update, update_fields=update_fields)
  File "/home/travis/virtualenv/python3.6.10/lib/python3.6/site-packages/django/db/models/base.py", line 776, in save_base
    update_fields=update_fields, raw=raw, using=using,
  File "/home/travis/virtualenv/python3.6.10/lib/python3.6/site-packages/django/dispatch/dispatcher.py", line 182, in send
    for receiver in self._live_receivers(sender)
  File "/home/travis/virtualenv/python3.6.10/lib/python3.6/site-packages/django/dispatch/dispatcher.py", line 182, in <listcomp>
    for receiver in self._live_receivers(sender)
  File "/home/travis/build/speedy-net/speedy-net/speedy/core/blocks/models.py", line 50, in remove_friends_on_block
    Friend.objects.remove_friend(from_user=instance.blocker, to_user=instance.blocked)
  File "/home/travis/virtualenv/python3.6.10/lib/python3.6/site-packages/friendship/models.py", line 368, in remove_friend
    qs.delete()
  File "/home/travis/virtualenv/python3.6.10/lib/python3.6/site-packages/django/db/models/query.py", line 728, in delete
    raise TypeError('Cannot call delete() after .distinct().')
TypeError: Cannot call delete() after .distinct().
```

I think calling .delete() after .distinct() is not allowed in Django >= 3.2.

https://travis-ci.org/github/speedy-net/speedy-net/builds/763787452

**Comment by uri-rodberg** [comment]
Also Django 3.2.

https://travis-ci.com/github/speedy-net/speedy-net/builds/224132810
