### ISSUE TITLE
Version 1.7.1 - running "manage.py migrate" throws an exception (when upgrading from 1.5.0).

### ISSUE THREAD

**Issue by urievenchen** [revsys/django-friendship#78]
Running migrations:
  Applying friendship.0002_auto_20180705_1444...Traceback (most recent call last):
  File ".venv\lib\site-packages\django\db\backends\utils.py", line 64, in execute
    return self.cursor.execute(sql, params)
psycopg2.ProgrammingError: relation "friendship_block" does not exist

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "speedy\net\manage.py", line 14, in <module>
    execute_from_command_line(sys.argv)
  File ".venv\lib\site-packages\django\core\management\__init__.py", line 364, in execute_from_command_line
    utility.execute()
  File ".venv\lib\site-packages\django\core\management\__init__.py", line 356, in execute
    self.fetch_command(subcommand).run_from_argv(self.argv)
  File ".venv\lib\site-packages\django\core\management\base.py", line 283, in run_from_argv
    self.execute(*args, **cmd_options)
  File ".venv\lib\site-packages\django\core\management\base.py", line 330, in execute
    output = self.handle(*args, **options)
  File ".venv\lib\site-packages\django\core\management\commands\migrate.py", line 204, in handle
    fake_initial=fake_initial,
  File ".venv\lib\site-packages\django\db\migrations\executor.py", line 115, in migrate
    state = self._migrate_all_forwards(state, plan, full_plan, fake=fake, fake_initial=fake_initial)
  File ".venv\lib\site-packages\django\db\migrations\executor.py", line 145, in _migrate_all_forwards
    state = self.apply_migration(state, migration, fake=fake, fake_initial=fake_initial)
  File ".venv\lib\site-packages\django\db\migrations\executor.py", line 244, in apply_migration
    state = migration.apply(state, schema_editor)
  File ".venv\lib\site-packages\django\db\migrations\migration.py", line 129, in apply
    operation.database_forwards(self.app_label, schema_editor, old_state, project_state)
  File ".venv\lib\site-packages\django\db\migrations\operations\models.py", line 536, in database_forwards
    getattr(new_model._meta, self.option_name, set()),
  File ".venv\lib\site-packages\django\db\backends\base\schema.py", line 369, in alter_unique_together
    self.execute(self._create_unique_sql(model, columns))
  File ".venv\lib\site-packages\django\db\backends\base\schema.py", line 136, in execute
    cursor.execute(sql, params)
  File ".venv\lib\site-packages\django\db\backends\utils.py", line 79, in execute
    return super(CursorDebugWrapper, self).execute(sql, params)
  File ".venv\lib\site-packages\django\db\backends\utils.py", line 64, in execute
    return self.cursor.execute(sql, params)
  File ".venv\lib\site-packages\django\db\utils.py", line 94, in __exit__
    six.reraise(dj_exc_type, dj_exc_value, traceback)
  File ".venv\lib\site-packages\django\utils\six.py", line 685, in reraise
    raise value.with_traceback(tb)
  File ".venv\lib\site-packages\django\db\backends\utils.py", line 64, in execute
    return self.cursor.execute(sql, params)
django.db.utils.ProgrammingError: relation "friendship_block" does not exist

(With Django 1.11 or 2.0)

**Comment by fcurella** [comment]
Looks like the `Block` model was added without a proper, separate migration in https://github.com/revsys/django-friendship/commit/109ae7d70d38a03808fa5c92325244afc77796c3

I'm trying to figure out the best way to handle this
